### ISSUE TITLE
Docker Image cannot access DNS

### ISSUE THREAD

**Issue by christcb03** [haruny/adt-pulse-mqtt#22]
For some reason the ADT Docker image cannot get DNS results. I have to log into the running container and change the DNS settings to my DNS server IP then it will work until it's restarted. I get this error in the logs.

2019-1-10 19:08:36 Pulse: Authentication bad response error:{"errno":"EAI_AGAIN","code":"EAI_AGAIN","syscall":"getaddrinfo","hostname":"portal.adtpulse.com","host":"portal.adtpulse.com","port":443}
2019-1-10 19:08:41 Pulse: Login called Authenticating
2019-1-10 19:08:46 Pulse.Sync: Sync stuck?

Then it repeats over and over.

**Comment by haruny** [comment]
sorry I don't know too much about docker maybe @digitalcraig can help?

**Comment by christcb03** [comment]
Is this not the ADT add-on for HASSIO? Aren't all HASSIO addons are inside docker containers? I really don't understand how it all works so it's likely I have some information wrong but I just installed HASSIO and then this plugin and it wouldn't work until I manually updated it.

**Comment by haruny** [comment]
you're right. I meant I dont know too much about docker to help.

**Comment by christcb03** [comment]
hmm so you don't know where the files inside the docker container for this addon come from?

**Comment by haruny** [comment]
your issue seems with docker or your specific hassio install.
The addon simply throws an error of not being able to access to the adt portal url.
The issue is not with the script.

**Comment by christcb03** [comment]
hmm strange, all the other docker containers have no problem connecting. guess I need to do more research into how they get their dns configs.

**Comment by haruny** [comment]
EAI_AGAIN seems to be a DNS timeout error.
maybe something weird going on with your hassio or your router, or your network.

try ssh'ing to your hassio instance and call:
`wget https://portal.adtpulse.com/myhome/13.0.0-153/access/signin.jsp` 

if it's working, check the hassio settings for the add-on. Mine works fine in protected mode.
Maybe an update of Hassio or a re-install of the addon may help.

sorry.

**Comment by christcb03** [comment]
Yeah I am not sure what is going on, my hass instance and everything else works fine. The setting for DNS inside the addon container though just isn't correct and is trying to look for DNS at a strange IP. If I change the /etc/resolv.conf file inside the container to the IP for my DNS server everything works fine until I have to restart the addon then that setting reverts and I have to do it again. I just know very little about docker and even less about how the addons work in hassio.

**Comment by digitalcraig** [comment]
Can you describe your setup? Is it Hassio on a raspberry pi? another platform/configuration?

**Comment by christcb03** [comment]
Actually I recently moved over to using an Ubuntu server with a docker image for HASSIO on it. I am sure that has something/everything to do with it since everything worked fine before the move. I have completely removed and reinstalled the addon but somehow the DNS settings still aren't working.

**Comment by digitalcraig** [comment]
There are a couple of things this could be, but you need to try to narrow it down to a resolver problem or a connectivity problem. Docker brings up it's own isolated network for containers to communicate with each other and handles name resolution between them. So it's possible other add-ons/containers may work while not being able to resolve DNS for external calls out such as with the ADT portal.

If it's resolver related, here are some leads to start with - https://serverfault.com/a/918568.

**Comment by christcb03** [comment]
I have confirmed it's a resolver problem and not a connectivity issue. I will check out the link you sent. Thank you very much!!

**Comment by christcb03** [comment]
So I finally had time to look at this again and found a new question. Which is how was everything else working? I found that the base server had an incorrect resolv.conf but even so was working for everything else. I have no idea how. Anyway I fixed that and restarted everything and now it's working fine. Thank you all for all the help!!
