### ISSUE TITLE
Compatible with hassio 095.4?

### ISSUE THREAD

**Issue by commandcontrolit** [haruny/adt-pulse-mqtt#28]
Hello, is this plugin compatible with hassio 0.95.4?

Can’t seem to get anything to work. 

I see the plugin is logging into my ADT portal. 

It doesn't seem to be pulling all the sensors when starting the plugin like it used to.

**Comment by vmweaver** [comment]
Are there specific sensors you are not seeing in Home Assistant? I just
restarted mine and am on current versions HA and the plugin. The logs show
everything operating as expected.
This plugin uses the Mosquito Plugin for message queuing to communicate
with HA. Do you know how to look at the MQTT messages to make sure that
system is healthy, too?

**Comment by commandcontrolit** [comment]
Strange, yes - all of my MQTT stuff is working, no issues. I wonder if my templates or sensors for the plugin have broken for some reason. 

Thanks - I'll keep at it!

**Comment by vmweaver** [comment]
I will say, though, that ADT has a way of rolling UI updates out for
customers, so you MAY be on a different version of the webpage that I am.
It may be worthwhile to keep this thread going until others can confirm.

**Comment by commandcontrolit** [comment]
Ok - makes sense. I just reopened.

**Comment by haruny** [comment]
What page version do you see in the logs? 
I confirm page version 15.0.0-130 works alright with Hassio 0.95.4

**Comment by commandcontrolit** [comment]
Hmmm.. I should be good then

/myhome/15.0.0-130/images/spacer.gif" border=0 width="1" height="15">

So this means it's my config. I'll close this. Thanks for the support.
