### ISSUE TITLE
ADT Pulse logon failure

### ISSUE THREAD

**Issue by robkjr** [haruny/adt-pulse-mqtt#37]
Totally new to this project but I've been looking for something to tie my ADT Pulse system with my Lutron Caseta lights.  Problem is I can't get past the initial log in.  I've installed v2.3.0 and set my configuration as follows.  

ssl: false
certfile: fullchain.pem
keyfile: privkey.pem
pulse_login:
  username: <known good UN>
  password: <known good PW>
mqtt_host: core-mosquitto
mqtt_url: ''
mqtt_connect_options:
  username: ''
  password: ''
alarm_state_topic: home/alarm/state
alarm_command_topic: home/alarm/cmd
zone_state_topic: adt/zone
smartthings_topic: smartthings
smartthings: false

This what I get in the log when I try to start the add-on.  Any help would be appreciated.  

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
> pulse-adt-mqtt@2.3.0 start /usr/src/app
> node server.js
5/21/2020, 7:55:46 PM Pulse.pulse Spanning
5/21/2020, 7:55:46 PM Pulse: New Client undefined
5/21/2020, 7:55:46 PM Pulse: Login called Authenticating
events.js:200
      throw er; // Unhandled 'error' event
      ^
Error: Connection refused: Not authorized
    at MqttClient._handleConnack (/usr/src/app/node_modules/mqtt/lib/client.js:920:15)
    at MqttClient._handlePacket (/usr/src/app/node_modules/mqtt/lib/client.js:350:12)
    at work (/usr/src/app/node_modules/mqtt/lib/client.js:292:12)
    at Writable.writable._write (/usr/src/app/node_modules/mqtt/lib/client.js:302:5)
    at doWrite (/usr/src/app/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/usr/src/app/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at Writable.write (/usr/src/app/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at Socket.ondata (_stream_readable.js:728:22)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
Emitted 'error' event on MqttClient instance at:
    at MqttClient._handleConnack (/usr/src/app/node_modules/mqtt/lib/client.js:922:10)
    at MqttClient._handlePacket (/usr/src/app/node_modules/mqtt/lib/client.js:350:12)
    [... lines matching original stack trace ...]
    at addChunk (_stream_readable.js:309:12) {
  code: 5
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pulse-adt-mqtt@2.3.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pulse-adt-mqtt@2.3.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by digitalcraig** [comment]
The error is that the add-on isn't able to authenticate with the Pulse Portal. The configuration you posted doesn't have anything in the pulse_login username and password fields. Is that because you removed them? Have you tested that you can login with those credentials on the Pulse Portal? 

Also, make sure your actual configuration is formatted as json.

```
{
      "pulse_login" : {
        "username": "you@email.com",
        "password": "yourpassword"
      },
      "mqtt_host" : "core-mosquito",
      "mqtt_connect_options" :  {
        "username" : "mqtt_user",
        "password" : "mqtt_password"
      },
      "alarm_state_topic": "home/alarm/state",
      "alarm_command_topic": "home/alarm/cmd",
      "zone_state_topic": "adt/zone",
      "smartthings_topic": "smartthings",
      "smartthings": false
}
```

**Comment by robkjr** [comment]
Craig, Sorry the config does have a known good UN and PW it just didn't past in that way.  when I used <> around it.   I just used the pattern in COnfiguration so I'll try to make it JSON.

**Comment by robkjr** [comment]
Ok so here's a screenshot of the configuration.  
![Capture](https://user-images.githubusercontent.com/51068706/82756146-58e8b880-9da6-11ea-825e-1fdb54ef7881.JPG)

**Comment by vmweaver** [comment]
I no longer have my pulse system, but did some work on this before.
The plugin, basically, scrapes the pulse pages and pushes meaningful
content to the MQTT topic.  Is the MQTT plugin running and configured without a user/password?

**Comment by robkjr** [comment]
Mosquitto Broker
![Capture](https://user-images.githubusercontent.com/51068706/82756363-d3660800-9da7-11ea-9cd1-87bd922f142e.JPG)

**Comment by robkjr** [comment]
Should Mosquitto have a username and password?

**Comment by vmweaver** [comment]
Change "anonymous" to "true" and restart MQTT and then restart the pulse plugin. This should tell us if that is the issue, but looking at the logs you posted, I am guessing it is.
Generally, it is a good idea to put a u/p on MQTT.
The reason for this is that control messages that this plugin picks up to arm/disarm you security system could be published to the topic by anyone/anything that knows about it and has network access.
Plus, it's just generally a really good idea.  I would even go so far as to dig into the SSL configuration to encrypt the network traffic.

**Comment by vmweaver** [comment]
To add a user to your MQTT config, get rid of the "[]" and have the YAML look something like this.

```
logins:
  - username: user
    password: passwd
```
Then in the Pulse config, use the same user/passwd as you did in the above config.

**Comment by robkjr** [comment]
> To add a user to your MQTT config, get rid of the "[]" and have the YAML look something like this.
> 
> ```
> logins:
>   - username: user
>     password: passwd
> ```
> 
> Then in the Pulse config, use the same user/passwd as you did in the above config.

This fixed it.  Thanks for the help.  Now my next goal is to connect my sensors with my lights.

**Comment by vmweaver** [comment]
@robkjr - Check out my friend's doorbell automation. This has some things that may help with that:
https://github.com/mcaminiti/homeassistant/blob/066bbc0bb4407c09795dff3bf6e631d5e57cec4d/automation/doorbell.yaml
Specifically the "Turn On Front Door when Motion Detected" section.

**Comment by digitalcraig** [comment]
@robkjr Glad you got it working. I'm remembering now that yaml and json are both acceptable for add-on configuration because they can be directly converted.

**Comment by robkjr** [comment]
> @robkjr - Check out my friend's doorbell automation. This has some things that may help with that:
> https://github.com/mcaminiti/homeassistant/blob/066bbc0bb4407c09795dff3bf6e631d5e57cec4d/automation/doorbell.yaml
> Specifically the "Turn On Front Door when Motion Detected" section.

Thanks.  I'm a complete noob to all this so I have a steep learning curve but this is very helpful.  One thing I do want to do is turn on my foyer/living room lights on when the front door is opened and then turn them off again in 10 minutes assuming the lights aren't already on.
