### ISSUE TITLE
Getting NULL JSON error in my logs now

### ISSUE THREAD

**Issue by sferguson524** [haruny/adt-pulse-mqtt#38]
This addon has been working flawlessly for months, and since HASS went to 112.0 code stream, i am seeign this in my logs 

Invalid Zone JSONTypeError: Cannot read property 'items' of null

**Comment by haruny** [comment]
I've seen this once on my side as well but it disappeared when I restarted it.
Do you mind posting your full logs? Just the relevant section. It should be dumping some html just before the line you've quoted.

**Comment by sferguson524** [comment]
Looks like it cleared up with an uninstall and reinstall
