### ISSUE TITLE
Adapt to Portal URL Changes:

### ISSUE THREAD

**Issue by haruny** [haruny/adt-pulse-mqtt#4]
When ADT releases a new version, the URL changes with the new version number. Call the hope page to grab the new version number and use the new formed url in the subsequent calls

**Comment by vmweaver** [comment]
As of today, I believe ADT has updated their URLs. I am getting:
https://portal.adtpulse.com/myhome/10.0.0-60/summary/summary.jsp

**Comment by haruny** [comment]
Yes. It actually started a few days ago. But apparently they didn’t deploy it to all their servers. Sometimes you get the older url randomly. 

I wrote a fix a few days ago already. I’m testing now.

**Comment by haruny** [comment]
0.2.1.0
