### ISSUE TITLE
::TypeError: Cannot read property '1' of null v.0.2.0.2

### ISSUE THREAD

**Issue by vmweaver** [haruny/adt-pulse-mqtt#8]
When starting this plugin I receive the following in the log output in HA:

```
2018-7-26 06:50:05 Pulse.pulse Spanning
2018-7-26 06:50:05 Pulse: New Client undefined
2018-7-26 06:50:05 Pulse: Login called Authenticating
MQTT Sub to: home/alarm/cmd
2018-7-26 06:50:06 Pulse: Authentication Success
2018-7-26 06:50:06 Pulse: updateAll
2018-7-26 06:50:06 Pulse.getAlarmStatus: Getting Alarm Statuses
2018-7-26 06:50:06 Pulse.Sync: Syncing 2-0-0
2018-7-26 06:50:06 Pulse: updateAll
2018-7-26 06:50:06 Pulse.getAlarmStatus: Getting Alarm Statuses
2018-7-26 06:50:06 Pulse: error getting sat ::
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
  .
  .
  .
 ::TypeError: Cannot read property '1' of null
```

I do not see MQTT messages hitting my queue. 

In looking through the code and testing running the code in NodeJS from a different computer, I can see that the REGEX for pulling out the "sat" value is returning "null" and I believe causing this error.

If I tweak the REGEX line to be:

`sat = body.match(/sat.(.+?(?='))/)[1];`

I start to see messages hitting my queue.

The snippet from the Response body showing the "sat" reference is the following (I have sanitized the “sat” number):

`setShiftState('changeModeRRA.jsp?sat=d123c456-abc7-89ca-a0ef-d4aa9b2f1d34','','');`

Please let me know if you need additional information.
Thanks.

**Comment by haruny** [comment]
Thanks. What's the version of the addon?

>2018-7-26 06:50:06 Pulse: error getting sat ::

could you submit the rest of the logs into https://gist.github.com and let me know the URL?

**Comment by vmweaver** [comment]
I updated to the latest after you just updated.
Will confirm version later, but believe it is 2.0.2.

**Comment by haruny** [comment]
thanks. I just need the full logs, showing that HTML you've shortened.

**Comment by haruny** [comment]
I checked again, your modified version for that regexp actually doesn't work on my Portal page.
I really need to see your summar.jsp output to find something that works both versions of this page.

please censor bits that of the page for your privacy with XXXXX such as Location name when you're sending it.

**Comment by vmweaver** [comment]
@haruny 
Thanks for looking at this.
https://gist.github.com/mawrew19/7e59e361ed8221ae48ee998d87efc7fc

**Comment by haruny** [comment]
On it.

**Comment by haruny** [comment]
attempted to fix in 0.2.1.1.
please give it a try and reopen if it doesn't work.

**Comment by vmweaver** [comment]
Works perfectly.
Thank you so much for your work on this project.  If you need additional
testing or anything else, I happy to help in any way I can to contribute to
this project.

**Comment by haruny** [comment]
Thank you. I just need more info for devices. If you have any devices in your account see:
https://github.com/haruny/adt-pulse-mqtt/issues/11
